// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/coral_word.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordRequest) Reset() {
	*x = WordRequest{}
	mi := &file_proto_coral_word_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRequest) ProtoMessage() {}

func (x *WordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coral_word_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRequest.ProtoReflect.Descriptor instead.
func (*WordRequest) Descriptor() ([]byte, []int) {
	return file_proto_coral_word_proto_rawDescGZIP(), []int{0}
}

func (x *WordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type Definition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           string                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Meaning       []string               `protobuf:"bytes,2,rep,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_proto_coral_word_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coral_word_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_proto_coral_word_proto_rawDescGZIP(), []int{1}
}

func (x *Definition) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *Definition) GetMeaning() []string {
	if x != nil {
		return x.Meaning
	}
	return nil
}

type Phrase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Example       string                 `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"`
	ExampleCn     string                 `protobuf:"bytes,2,opt,name=example_cn,json=exampleCn,proto3" json:"example_cn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phrase) Reset() {
	*x = Phrase{}
	mi := &file_proto_coral_word_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phrase) ProtoMessage() {}

func (x *Phrase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coral_word_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phrase.ProtoReflect.Descriptor instead.
func (*Phrase) Descriptor() ([]byte, []int) {
	return file_proto_coral_word_proto_rawDescGZIP(), []int{2}
}

func (x *Phrase) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Phrase) GetExampleCn() string {
	if x != nil {
		return x.ExampleCn
	}
	return ""
}

type WordDesc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Pronunciation string                 `protobuf:"bytes,3,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Definitions   []*Definition          `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Derivatives   []string               `protobuf:"bytes,5,rep,name=derivatives,proto3" json:"derivatives,omitempty"`
	ExamTags      []string               `protobuf:"bytes,6,rep,name=exam_tags,json=examTags,proto3" json:"exam_tags,omitempty"`
	Example       string                 `protobuf:"bytes,7,opt,name=example,proto3" json:"example,omitempty"`
	ExampleCn     string                 `protobuf:"bytes,8,opt,name=example_cn,json=exampleCn,proto3" json:"example_cn,omitempty"`
	Phrases       []*Phrase              `protobuf:"bytes,9,rep,name=phrases,proto3" json:"phrases,omitempty"`
	Synonyms      []string               `protobuf:"bytes,10,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Source        int32                  `protobuf:"varint,11,opt,name=source,proto3" json:"source,omitempty"`
	WordId        int64                  `protobuf:"varint,12,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordDesc) Reset() {
	*x = WordDesc{}
	mi := &file_proto_coral_word_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordDesc) ProtoMessage() {}

func (x *WordDesc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coral_word_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordDesc.ProtoReflect.Descriptor instead.
func (*WordDesc) Descriptor() ([]byte, []int) {
	return file_proto_coral_word_proto_rawDescGZIP(), []int{3}
}

func (x *WordDesc) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *WordDesc) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordDesc) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *WordDesc) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *WordDesc) GetDerivatives() []string {
	if x != nil {
		return x.Derivatives
	}
	return nil
}

func (x *WordDesc) GetExamTags() []string {
	if x != nil {
		return x.ExamTags
	}
	return nil
}

func (x *WordDesc) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *WordDesc) GetExampleCn() string {
	if x != nil {
		return x.ExampleCn
	}
	return ""
}

func (x *WordDesc) GetPhrases() []*Phrase {
	if x != nil {
		return x.Phrases
	}
	return nil
}

func (x *WordDesc) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *WordDesc) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *WordDesc) GetWordId() int64 {
	if x != nil {
		return x.WordId
	}
	return 0
}

var File_proto_coral_word_proto protoreflect.FileDescriptor

const file_proto_coral_word_proto_rawDesc = "" +
	"\n" +
	"\x16proto/coral_word.proto\x12\n" +
	"coral_word\"!\n" +
	"\vWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"8\n" +
	"\n" +
	"Definition\x12\x10\n" +
	"\x03pos\x18\x01 \x01(\tR\x03pos\x12\x18\n" +
	"\ameaning\x18\x02 \x03(\tR\ameaning\"A\n" +
	"\x06Phrase\x12\x18\n" +
	"\aexample\x18\x01 \x01(\tR\aexample\x12\x1d\n" +
	"\n" +
	"example_cn\x18\x02 \x01(\tR\texampleCn\"\x83\x03\n" +
	"\bWordDesc\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12$\n" +
	"\rpronunciation\x18\x03 \x01(\tR\rpronunciation\x128\n" +
	"\vdefinitions\x18\x04 \x03(\v2\x16.coral_word.DefinitionR\vdefinitions\x12 \n" +
	"\vderivatives\x18\x05 \x03(\tR\vderivatives\x12\x1b\n" +
	"\texam_tags\x18\x06 \x03(\tR\bexamTags\x12\x18\n" +
	"\aexample\x18\a \x01(\tR\aexample\x12\x1d\n" +
	"\n" +
	"example_cn\x18\b \x01(\tR\texampleCn\x12,\n" +
	"\aphrases\x18\t \x03(\v2\x12.coral_word.PhraseR\aphrases\x12\x1a\n" +
	"\bsynonyms\x18\n" +
	" \x03(\tR\bsynonyms\x12\x16\n" +
	"\x06source\x18\v \x01(\x05R\x06source\x12\x17\n" +
	"\aword_id\x18\f \x01(\x03R\x06wordId2N\n" +
	"\x10CoralWordService\x12:\n" +
	"\tQueryWord\x12\x17.coral_word.WordRequest\x1a\x14.coral_word.WordDescB'Z%github.com/byBit-ovo/coral_word/pb;pbb\x06proto3"

var (
	file_proto_coral_word_proto_rawDescOnce sync.Once
	file_proto_coral_word_proto_rawDescData []byte
)

func file_proto_coral_word_proto_rawDescGZIP() []byte {
	file_proto_coral_word_proto_rawDescOnce.Do(func() {
		file_proto_coral_word_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coral_word_proto_rawDesc), len(file_proto_coral_word_proto_rawDesc)))
	})
	return file_proto_coral_word_proto_rawDescData
}

var file_proto_coral_word_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_coral_word_proto_goTypes = []any{
	(*WordRequest)(nil), // 0: coral_word.WordRequest
	(*Definition)(nil),  // 1: coral_word.Definition
	(*Phrase)(nil),      // 2: coral_word.Phrase
	(*WordDesc)(nil),    // 3: coral_word.WordDesc
}
var file_proto_coral_word_proto_depIdxs = []int32{
	1, // 0: coral_word.WordDesc.definitions:type_name -> coral_word.Definition
	2, // 1: coral_word.WordDesc.phrases:type_name -> coral_word.Phrase
	0, // 2: coral_word.CoralWordService.QueryWord:input_type -> coral_word.WordRequest
	3, // 3: coral_word.CoralWordService.QueryWord:output_type -> coral_word.WordDesc
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_coral_word_proto_init() }
func file_proto_coral_word_proto_init() {
	if File_proto_coral_word_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coral_word_proto_rawDesc), len(file_proto_coral_word_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coral_word_proto_goTypes,
		DependencyIndexes: file_proto_coral_word_proto_depIdxs,
		MessageInfos:      file_proto_coral_word_proto_msgTypes,
	}.Build()
	File_proto_coral_word_proto = out.File
	file_proto_coral_word_proto_goTypes = nil
	file_proto_coral_word_proto_depIdxs = nil
}
